
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD AND ARRAY ASSIGN AUTO BOOLEAN BOOLEANLIT BREAK CL CM CONCATE CONTINUE DIV DO DOT ELSE EQUAL FLOAT FLOATLIT FOR FUNCTION GE GT ID IF INHERIT INTEGER INTLIT LB LE LP LSB LT MOD MUL NOT NOT_EQUAL OF OR OUT RB RETURN RP RSB SM STRING STRINGLIT SUB VOID WHILEexpr : expr ADD expr\n            | INTLIT\n            | ID'
    
_lr_action_items = {'INTLIT':([0,4,],[2,2,]),'ID':([0,4,],[3,3,]),'$end':([1,2,3,5,],[0,-2,-3,-1,]),'ADD':([1,2,3,5,],[4,-2,-3,4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,4,],[1,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr ADD expr','expr',3,'p_expr','ParserBuilder.py',8),
  ('expr -> INTLIT','expr',1,'p_expr','ParserBuilder.py',9),
  ('expr -> ID','expr',1,'p_expr','ParserBuilder.py',10),
]
